### PR TITLE
Bump to 3.5.0 and enable external static linking

### PR DESCRIPTION
**Pull request by thillux**
This PR contains some changes/fixes we use with botan-rs.

* We experienced ECDSA verification errors with the vendored botan version 3.1.1 and therefore bumped to the latest available  version of botan, where these issue where gone. These errors did not happen when using a non-vendored more recent version of botan 3.
* We'd like to build static Rust-based binaries with help of the musl libc and different build settings than set on the vendored botan 3 (e.g. build it with the BSI module policy). I therefore added some small features to enable external static linking and optional path lookup with pkg-config.

### CODE REVIEW

**Comment by thillux** [comment]
Commits are signed now.

**Comment by randombit** [comment]
Thank you looks very good.

There was some CI bitrot, please rebase against master to pick up #121 

I think the `dep:` introduction causes us to have to increase MSRV to 1.60.0, which seems fine at this point, that's already 2+ years old. IIRC that specific MSRV was introduced for Sequoia but they seem to already have an MSRV of 1.67 now. However given this please also update the relevant `rust-versions`, MSRV statement in README, etc

[Unless there's an easy fix to avoid an MSRV bump, which would maybe be preferable since I guess technically an MSRV bump would require also bumping the minor version]

**Comment by randombit** [comment]
[OTOH a MSRV bump would be a good time to also merge #104 so maybe we should just do that]

**Comment by thillux** [comment]
I rebased and did fmt + clippy. CI was green on my own fork.

**Review by randombit — APPROVED** [review]
Looks good, thanks for the contribution @thillux

**Pull request merged**
