### PR TITLE
Support incremental update

### PR DESCRIPTION
**Pull request by chux0519**
Add support for incremental update

I'll add more test cases when I'm free

### CODE REVIEW

**Comment by chux0519** [comment]
It seems something wrong with ci

```
$ ./.ci/install_botan.sh
Cloning into 'botan'...
remote: Enumerating objects: 2870, done.
remote: Counting objects: 100% (2870/2870)   remote: Counting objects: 100% (2870/2870), done.
remote: Compressing objects: 100% (2376/2376)   remote: Compressing objects: 100% (2376/2376), done.
Receiving objects:  99% (2842/2870), 6.55 MiB | 13.09 MiB/s   remote: Total 2870 (delta 455), reused 1644 (delta 409), pack-reused 0
Receiving objects: 100% (2870/2870), 6.55 MiB | 13.09 MiB/s   Receiving objects: 100% (2870/2870), 7.35 MiB | 13.59 MiB/s, done.
Resolving deltas: 100% (455/455)   Resolving deltas: 100% (455/455), done.
   INFO: ./configure.py invoked with options "--disable-static --without-documentation --with-debug-info"
   INFO: Autodetected platform information: OS="Linux" machine="x86_64" proc="x86_64"
   INFO: Guessing target OS is linux (use --os to set)
  ERROR: Could not figure out what compiler type 'ccache g++' is, use --cc to set
make: *** No rule to make target `libs'.  Stop.
make: *** No rule to make target `install'.  Stop.
```

**Comment by randombit** [comment]
Thank you! I will review this asap and also investigate the problem with CI.

**Comment by randombit** [comment]
As always, more tests would be great, but this looks ok to me so I'm merging. Thanks again.

**Comment by chux0519** [comment]
Very happy to make small contribution to this project.

**Pull request merged**
