### PR TITLE
Support DSA, ElGamal, non-allocating interface for Cipher

### PR DESCRIPTION
**Pull request by teythoon**
While porting Sequoia-PGP to Botan, I had to amend the bindings a little.

Work in progress backend: https://gitlab.com/sequoia-pgp/sequoia/-/commit/11ca5a66a257202179642b7e361eb9e6f3fbb754

The first two commits add support for loading DSA and ElGamal keys, respectively.  The last commit adds an interface to `Cipher` that allows decryption and encryption without returning the result as a `Vec<u8>`.

Thanks for your consideration!

### CODE REVIEW

**Comment by teythoon** [comment]
Duh, I forgot a debugging remnant :/ will fix that soon.

**Review by randombit — COMMENTED** [review]
This looks really good, thanks!

Can you please add some simple tests, especially of the new cipher handling? Otherwise lgtm.

Big fan of Sequoia btw, the PGP ecosystem has been stalled far too long

**Comment by teythoon** [comment]
Thanks for the feedback and the flowers :)

I'm happy to add some tests!

**Review by randombit — APPROVED** [review]
Looks great, thanks for adding the tests!

**Comment by randombit** [comment]
@teythoon Just to follow up here, this patch was included in the 0.10.1 crate which was just released. Additionally that version manages to reduce the MSRV (at least for non `no-std` builds) to 1.58

**Comment by teythoon** [comment]
Thanks for the quick response and release.  Lowering the MSRV is also appreciated.  I merged the Botan support into Sequoia and it will be part of the next release of the `sequoia-openpgp` crate.  I think it turned out to be quite clean.

https://gitlab.com/sequoia-pgp/sequoia/-/commit/336a1562bfe3ad5fe32b5e3017c88197f5bad0fa

**Pull request merged**
